name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v2
        with:
          go-version: ~1.17

      - name: Install Git SemVer
        run: go install .
        
      - id: release-bot
        name: Authenticate with Release Bot
        uses: getsentry/action-github-app-token@v1
        with:
          app_id: ${{ secrets.CB_RELEASE_BOT_ID }}
          private_key: "${{ secrets.CB_RELEASE_BOT_PRIVATE_KEY }}"
        
      - name: Setup Git Credentials
        uses: fusion-engineering/setup-git-credentials@v2
        with:
          credentials: https://carlsberg-release-bot[bot]:${{ steps.release-bot.outputs.token }}@github.com/

      - name: Bump Version
        run: |
          git config --global user.name "${{ secrets.CB_RELEASE_BOT_NAME }}"
          git config --global user.email "${{ secrets.CB_RELEASE_BOT_EMAIL }}"
          git semver bump

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ steps.release-bot.outputs.token }}
